#!/bin/bash

ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-"localhost:9200"}

for query in $(ls -1 query*.json); do
    echo "START ---------------- ${query} ----------------"
    curl -sS -XPOST "${ELASTICSEARCH_HOST}/movies/movie/_search" --data @"$query" | jq .
    echo "END   ---------------- ${query} ----------------"
done
